import { z } from "zod";

export const workExperienceSchema = z.object({
  company: z.string(),
  link: z.string().nullish(),
  role: z.string(),
  startDate: z.date(),
  endDate: z.date().nullish(),
  description: z.array(z.string()),
  technologies: z.array(z.string()),
  location: z.string().nullish(),
});

export type workExperienceType = z.infer<typeof workExperienceSchema>;

export const workExperience = [
  {
    company: "Elcia",
    link: "https://www.elcia.com/",
    role: "Apprenticeship Full Stack Developer",
    startDate: new Date("2022-06-20"),
    endDate: new Date("2025-09-19"),
    description: [
      "Creation of an internal internationalization system.",
      "Creation of an API for calculating eco-participation on invoices.",
      "Maintenance and evolution of an order service.",
    ],
    technologies: [
      "dotnet",
      "React",
      "typescript",
      "nodedotjs",
      "nginx",
      "sonarqube",
      "git",
      "github",
      "docker",
      "figma",
      "dbeaver",
      "reacthookform",
      "reactquery",
      "zod",
    ],
    location: "Brignais, France",
  },
  {
    company: "TechMotion",
    role: "Co-Founder",
    startDate: new Date("2025-03"),
    endDate: null,
    description: [
      "Creation of a boilerplate for Next.js projects with Shadcn UI, Prisma ORM, Framer Motion, BetterAuth and Vercel.",
      "Creation of trainings on Next.js and the boilerplates.",
    ],
    technologies: [
      "Next.js",
      "TypeScript",
      "tailwindcss",
      "shadcnui",
      "prisma",
      "framer",
      "vercel",
      "docker",
      "git",
      "2fas",
      "github",
      "dbeaver",
      "postgresql",
      "reacthookform",
      "reactquery",
      "zod",
    ],
  },
  {
    company: "From-A2B",
    role: "Freelance Full Stack",
    startDate: new Date("2024-12"),
    description: ["Creation of a travel planning application"],
    technologies: [
      "Next.js",
      "TypeScript",
      "tailwindcss",
      "shadcnui",
      "prisma",
      "framer",
      "vercel",
      "git",
      "2fas",
      "github",
      "docker",
      "dbeaver",
      "postgresql",
      "reacthookform",
      "reactquery",
      "zod",
    ],
    location: "At home",
  },
  {
    company: "Codeline",
    role: "Freelance Full Stack",
    startDate: new Date("2024-12"),
    description: [
      "Maintenance of an online training platform",
      "Setting up a progress tracking system with webhooks between the training platform and Discord.",
    ],
    technologies: [
      "Next.js",
      "TypeScript",
      "tailwindcss",
      "shadcnui",
      "docker",
      "prisma",
      "framer",
      "vercel",
      "git",
      "github",
    ],
  },
] satisfies workExperienceType[];
