import { ContactDialog } from "@components/contact/contactDialog";
import { Footer } from "@components/layout/footer";
import { Navbar } from "@components/layout/navbar";
import { NextTopLoader } from "@components/page/nextTopLoader";
import { TailwindIndicator } from "@components/utils/tailwindDevIndicator";
import { cn } from "@lib/utils";
import type { LayoutParams } from "@type/next";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import { Providers } from "./providers";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: LayoutParams) => {
  return (
    <html lang="en" className="h-full" suppressHydrationWarning>
      <header>
        <Navbar />
      </header>
      <body
        suppressHydrationWarning
        className={cn(
          "bg-background h-full font-sans antialiased",
          geistMono.variable,
          geistSans.variable,
        )}
      >
        <Providers>
          <Toaster />
          {children}
          <TailwindIndicator />
          <NextTopLoader />
          <ContactDialog />
        </Providers>
      </body>
      <footer>
        <Footer />
      </footer>
    </html>
  );
};

export default RootLayout;
